### PR TITLE
Typo fix.

### PR DESCRIPTION
**Pull request by NGCMan**

### CODE REVIEW

**Comment by usavictor210** [comment]
if you want you can help with development

**Comment by NGCMan** [comment]
I'm not very good with JavaScript, but I'm good at HTML and some CSS.
(And JavaScript is what's used to make the game.)
Thanks for the offer!

**Comment by usavictor210** [comment]
you're welcome

**Comment by NGCMan** [comment]
I know that Nyan cat (e666666) is good at JavaScript, in case you're looking for someone to help, but I guess I can try.

**Pull request merged**
